### ISSUE TITLE
Consistent policy re: duplicate names

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#124]
In some functions, we don't let you create a file "foo" if "foo" already exists. Examples:

  * *I think `drive_upload()`?*

In others, we silently let this happen:

  * `drive_mkdir()`

In googlesheets, I've always thrown a warning or message, when people do this, so they know they have >1 file with the same name.

We need to take a position on this and be consistent everywhere.

**Comment by LucyMcGowan** [comment]
I *think* `drive_upload()` is the only one where we currently don't allow this (because `drive_rename()` for example doesn't actually check that it isn't already named that). It makes the most sense to me to force the user to think about whether they really meant to have 2 files with the same name (or just do not allow it at all) -- if you agree I'll add a check in `drive_mkdir()` and `drive_rename()` to disallow this.

**Comment by jennybc** [comment]
We've settled on allowing this, i.e. allowing the user to create two things with the same name, in the same folder. Jury is still out re: whether we want to message or warn about it. In general, it would require extra API calls, to check for this situation, hence we are ambivalent.

**Comment by jennybc** [comment]
No near term plans to do anything here.
