### ISSUE TITLE
Understanding publishing

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#136]
So I (think I) understand the implications of publishing for a Google Sheet.

But what does it mean in general? Can you publish an arbitrary file?

**Comment by LucyMcGowan** [comment]
* [What is publishing?](https://support.google.com/docs/answer/37579?co=GENIE.Platform%3DDesktop&hl=en) After publishing you can send a link or embed in a website
* [What's the difference between Publishing and Sharing?](https://sites.google.com/a/ohlsd.org/google-apps-training/google-docs-introduction/google-docs-before-you-begin/what-s-the-difference-between-publishing-and-sharing)
> When you publish a doc, Google Docs creates a separate, lightweight webpage where anyone with the link can view the contents of your document. Because the published version of a doc is its own webpage with its own URL, that version isn’t affected by the visibility option you choose for your document.
_It seems with team drives, an admin can control whether documents are published to the world or published to the domain._
* Without a published doc, it seems you cannot embed as an HTML doc.
* I've played with an unpublished spreadsheet that is not "mine". Here is what I found:
   * *If it is unpublished, but "anyone with the link can view"*: I can use `drive_get()` using the link and access the metadata. I am not able to make any updates (which makes sense since the sharing is only set to viewing)
* *If it is unpublished, but "anyone with the link can edit"*: I can use `drive_get()` to access it, and I am able to update things like metadata using `drive_update()`.

**Comment by jennybc** [comment]
From <https://developers.google.com/drive/v3/web/manage-revisions> I gather that only "native" files can be published. We should document that.

> For Google Docs, Sheets, and Slides you can publish any revision to the web by setting the published property.

**Comment by LucyMcGowan** [comment]
Yikes yes, we check for this in the function itself but I see we don't actually mention it in the docs 🙊

**Comment by jennybc** [comment]
While I was experimenting with auth, I also (think I) determined that a Google Doc that is published but not shared cannot be `drive_get()`'d by id by someone who is not logged in (I was sending API key only, no token). Once I shared it with anyone, I could.

Since I was working on something else, I didn't carefully pursue all possible permutations of file permissions * logged-in-ness, but we should do a small systematic study of this.

**Comment by LucyMcGowan** [comment]
@jennybc I'll look into that 👆

**Comment by jennybc** [comment]
Oh don't even get me started on the whole "published to the web" vs "public on the web" thing with Sheets. I believe this only applies to the v3 Sheets API. At least I hope so. It was a regrettable decision.

But yes when/if we make this matrix, we must also contemplate differences between Docs and Sheets. I.e. are we going to try `drive_get()` or `drive_download()` or (for sheets) something that reads specific cells? Because I would not be surprised if this reveals differences in behaviour.

**Comment by jennybc** [comment]
There's not exactly a specific call to action here. Closing.
