### ISSUE TITLE
recursively list files in drive

### ISSUE THREAD

**Issue by stfriedman** [tidyverse/googledrive#174]
I'm trying to figure to mimic the recursiveness of the list.files function in googledrive. I've tried using drive_find but I need a way to store file paths as well. Any ideas?

**Comment by jennybc** [comment]
You can use `drive_find()` to get *everything* on your drive. And if you'd like to add paths, do this:

```r
drive_find() %>% drive_add_path()
```

It may be slow-ish because there's recursive work going on in the background. Drive files only know who their direct parents are. So to build a path, you must walk up the "tree" for each file. I put "tree" in quotes, because the Drive file system is not hierarchical, like your local one. Folders are more like gmail labels. A file can have multiple folders as direct parent and, therefore, can be represented by multiple paths. Yours are probably not that weird, however 😄.

Also, I should warn you, the name of `drive_add_path()` might change. But the functionality will remain.

**Comment by jennybc** [comment]
To list the direct children of a folder, use `drive_ls()`. But I gather from your question that direct children may not be enough.

**Comment by jennybc** [comment]
I'm curious if the above was helpful to you? What is your exact use case?

Note that `drive_add_path()` is, now, `drive_reveal(x, "path")`.

I'm following up because this will go to CRAN soon and I *could* add recursive option to `drive_ls()`. Trying to decide if it's worth it right now ...

**Comment by stfriedman** [comment]
So sorry to not respond and thanks a ton for your help! While it was working for my friend, I was actually getting a strange error (Result 1 is not a length 1 atomic vector) with `drive_add_path()`. Looking into the error more seemed to indicate that it was an underlying issue with `map_chr()`, but I didn't get much deeper than that. It very well may have been something I was doing wrong. 

Since I already had all the names of the files I needed, I actually just ended up generating all of the path names and using `drive_ls()` in conjunction with `sapply()` to brute force a sort of recursive function. Got it all working just fine, though a built-in recursive option would always be useful! 

By the way, the package is just great -- it saved me a ton of time this summer. Thanks again for your help.

**Comment by stfriedman** [comment]
Oops missed your other question. We're basically generating a database of photographs of specimens on google drive as well as a data set of morphological data for each specimen. I'm just trying to make sure that each measured specimen also has a photo stored in google drive. Hence, I just needed a list of the files names present in drive for comparison.
