### ISSUE TITLE
Slow performance for very large Drive

### ISSUE THREAD

**Issue by jarodmeng** [tidyverse/googledrive#201]
I have a very large Drive (~30G) having 10,000+ documents. I notice that using `drive_*()` with character paths often have performance issues dealing with very large Drive (e.g., a simple `drive_upload()` of a small file takes  2+ min to complete).

I did a bit digging and find that usually the culprit is [`drive_get()`](https://github.com/tidyverse/googledrive/blob/master/R/drive_get.R#L64). In particular, [`dribble_from_path()`](https://github.com/tidyverse/googledrive/blob/5e653c1115511281a45b97ee04df819a596f84b0/R/drive_reveal_path.R#L47) and [`get_nodes()`](https://github.com/tidyverse/googledrive/blob/5e653c1115511281a45b97ee04df819a596f84b0/R/drive_reveal_path.R#L89) can be very slow.

Is this a known issue? I don't know how much of this performance issue is simply due to my Drive being too large and how much can be addressed by improving the code. I can do a bit more digging and experiments, but also want to raise the issue early to hear from others.

**Comment by jennybc** [comment]
I'm sorry to say that this does not surprise me. If you identify files by name or path, we have to do a lot of work behind the scenes that is definitely influenced by the number of files you have (their *size* should not matter).

You should have a much better result if you identify files by id, as early as possibly in the process. The most humane way to do that is to use a URL and provide that to googledrive functions, wrapped in `as_id()`. Once we have the files in a dribble, we have the id, and things should be faster.

Depending on how you can specify your files, using `drive_find()` with search clauses might also help.

Short of that, we do have batch requests on the radar (#126), which could possibly help.

If you can provide more detail on what you're trying to do, I might be able to be more specific.

**Comment by jarodmeng** [comment]
Identifying a file/folder by ID is exactly what I resorted to. However, it's still unintuitive and a hassle to get the URL or ID in interactive use. Most of my use case fall into programming using `drive_*()` functions. For instance, I have a `ggsave.drive()` function via which I can save ggplot charts to my Drive folder for easy sharing. I would like to avoid having to ask users to provide URL or ID directly as much as possible.

I tried to read through the code and see where the bottleneck might be. It seems to me that [`get_nodes()`](https://github.com/tidyverse/googledrive/blob/master/R/drive_reveal_path.R#L89) is a heavy operation for large Drive because [`q_clauses`](https://github.com/tidyverse/googledrive/blob/master/R/drive_reveal_path.R#L102) basically gets *all* folders in Drive into a dribble every time it's called. In my case, it returns ~3100 folders, even when I asks for a very specific folder. In my functions, I resort to using `drive_find()` with `pattern` to quickly narrow it down to possible folders rather than operating on all folders. I was wondering if `get_nodes()` can be modified to make it more efficient/scalable for large Drive users.

**Comment by jennybc** [comment]
There was an earlier version of `get_nodes()` (or, at least, that functionality) that requested the intersection of folders AND file name being an element of the putative path. I simplified to the current "all folders" version in one of my many refactorings, with the logic of "avoid premature optimization". It does make the code simpler. I knew we could always add the complexity back if it seemed to matter in real life. You seem to be telling me it does.

If you're eager, you might be able to find this version and patch that in and see if it helps in your case. I suspect it will with ~3100 folders! But I have a feeling that logic existed when the path resolution code was quite different overall.

Otherwise, I will do this, but there's no way I can do it in the next week or two.

**Comment by jennybc** [comment]
I still don't have an exact idea of what you're doing.

But if you or your user is willing to give exact filename (folder name?), can you not use `drive_find(q = "name = 'hello'")` to get that file and therefore it's id (add a folder constraint, if relevant)? You could even consider a search clause more along the lines of `name contains 'hello'`, to be a bit fuzzier.

**Comment by dsdaveh** [comment]
... excuse me, I couldn't help overhearing ... I've encountered the issue of performance with large Drive bases as well. One of the first things I discovered was that drive_find(n_max = 1000 ...) sped up performance dramatically(I originally had 35K+ files) without much loss since the sorting seems to be chronological. But, I also had over 3K folders, so saw some operations still took a long time when they needed to cut through my folders.  At the time I was going to suggest/hack some sort of caching mechanism so those operations only need to be performed once and the resulting dribbles could be updated relatively painlessly. The cache could be stored as an .rds file in Drive so it spans user sessions. In the end I just ended up [cleaning up my drive, a task made much easier with the googledrive package](https://github.com/dsdaveh/gdrive-viewer/blob/master/reducing_drive_quota.md). Now I'm down to ~7K files and 350 folders, so the caching idea isn't as high a priority for me, but there might be other cases where it could help.

FWIW: My file explosion came primarily from a brief period in 2014 when I took the plunge into GitHub, but didn't decouple those repo folders from desktop Drive folders (storing the cloud in the cloud  is not a good look).

**Comment by jennybc** [comment]
Caching had crossed my mind but I don't think it can be done in a naive way. You'd need to be somehow watching for changes in the user's Drive and updating your cache, because there's no guarantee that other processes aren't adding files, deleting them, etc.

**Comment by dsdaveh** [comment]
deleting <sigh>, yes that complicates things. My initial thoughts were to just put the caching options in the hands of the user, who should have a decent feel for how their Drive content is changing. As I mentioned, I was able to (mostly) eliminate my pain through cleanup, so I haven't put much thought into all the use cases and whether a naive solution would solve a disproportionate chunk of issues.

**Comment by jarodmeng** [comment]
Thanks, @jennybc . I'm now using `drive_find()` with `pattern` to find the folder using the folder name supplied by the user. After the specific folder is located, everything works very fast and reliably. I plan to take a stab at how `drive_get()` can find a particular needle in the haystack more efficiently and submit a PR. Thanks for another great package!
