### ISSUE TITLE
Authorizing multiple virtual machines from local session

### ISSUE THREAD

**Issue by ctlamb** [tidyverse/googledrive#224]
I understand that I can store a token from my local, authorized sessions as explained  [here](https://googledrive.tidyverse.org/reference/drive_auth.html):

```
## store token in an object and then to file
ttt <- drive_auth()
saveRDS(ttt, "ttt.rds")

## load a pre-existing token
drive_auth("ttt.rds") # from .rds file
```

Information and objects from the local session can be uploaded tothe VM's (setup with doAzureParallel), but these objects need to be in the local r environment. I tried to load the saved .RDS file as an object and then pass that object along to the VM, but drive_auth() expects a path and  fails

```
ttt <- drive_auth()
saveRDS(ttt, "ttt.rds")
a <-readRDS("ttt.rds")
drive_auth(a)     *could just be ttt too
Error: is_string(oauth_token) is not TRUE
```

Any thoughts?

**Comment by jennybc** [comment]
Bear with me, because I don't know anything about doAzureParallel.

But you need to make the file `ttt.rds` available to the R session on the VM. The way this function is designed, it expects to either kick off OAuth flow, ingest a service token, or get *a path* to an `.rds` file holding a stored OAuth token (in the httr sense).

If you must work with an R object (so, `ttt`, above), you could probably use the unexported function `googledrive:::set_access_cred()` to put it into force. But, as the "unexported" part suggests, that's not an officially supported workflow.

I would assume that the Azure workflow supports uploading of files?

**Comment by ctlamb** [comment]
Thanks @jennybc, that helps. I will just host `ttt.rds` on dropbox and send the link to the file to the VM, download then load via that downloaded path.

Thanks!

**Comment by jennybc** [comment]
> host `ttt.rds` on dropbox

Let me know how this goes. This token has full authority to access Google Driven your behalf, so you should definitely treat it with some care.

You might also be a good candidate for using a service account. This would allow you to get a different type of token that is inherently better suited to non-interactive use. See #225 for a similar conversation with another user.

**Comment by jennybc** [comment]
I'm going to close this and let #239 be the issue for non-interactive auth. This will be different -- hopefully much more straightforward! -- in the next release, once [gargle](https://gargle.r-lib.org) is on CRAN and I can release an update to googledrive. The dev version of googledrive has already switched over.
