### ISSUE TITLE
Work with Google Drive File Stream?

### ISSUE THREAD

**Issue by efh0888** [tidyverse/googledrive#246]
My company won't give me Google Drive API access, so is it possible to interact through this R package with files sitting in a local Google Drive File Stream? Specifically want to programmatically set permissions for new files generated from an R script.

**Comment by jennybc** [comment]
I don't know anything about Google Drive File Stream. Do you have a favourite resource that serves as an explainer?

**Comment by efh0888** [comment]
It's pretty new to me as well, but this explains at a fairly high level - https://techcrunch.com/2017/09/07/google-launches-drive-file-stream-to-replace-the-google-drive-desktop-app-for-g-suite-users/.

But basically it's an enterprise tool that allows you to map Drive to a local drive and can auto sync (with some delay). Without API access, it seems to be the only way to interact with Drive from R.

**Comment by jennybc** [comment]
This feels DropBox-y? Have you confirmed that you can't use base R file system functions or the fs package to edit these permissions?

**Comment by efh0888** [comment]
Yeah, you're right, it is kind of Dropbox-y. And no, I haven't looked into either of those options. I can check out fs, but I'm trying to share the file with someone in my organization based on email address, so I'm not sure if that's doable.

**Comment by jennybc** [comment]
> share the file with someone in my organization based on email address

Oh, I see. So Drive-specific sharing permissions.

**Comment by jennybc** [comment]
This is not a clear googledrive issue, but I'd be happy to discuss again in future, if we can identify a plausible and fruitful connection between this package and Google Drive File Stream.

**Comment by py9mrg** [comment]
A bit late to the party but I was wondering if it's worth re-opening this issue (or moving it to a googlesheets4 issue)? To confirm Google Drive File Stream is essentially Google's answer to Dropbox, basically it installs a local drive (usually "G:\", at least in Windows) on your computer and then you can use this like Dropbox, with both "normal" files and Google docs/sheets etc syncing with your G Drive account.

In theory then, if googledrive (or googlesheets4) can read/write to this local drive, and then leave that to deal with syncing to G Drive, it removes a lot of the auth hassle for users/app creators. For example, I want to make a layman's shiny app using the fantastic [electricShine](https://chasemc.github.io/electricShine/) to combine R/shiny etc with electron. I want to be able to give this to colleagues and let them use it to read/write from their own G Drive. I'm having a problem because the resulting electron app won't trigger a web browser opening - presumably an electron thing, but could be that I've done something daft - and I am trying to avoid them the hassle of installing R themselves and getting their own token. I am in the process of researching a better solution to this in the gargle docs, but the easiest would be to tell them to install GDFS and then let gs4 read/write to that.

I'm not sure if it's going to be so easy though as I am guess Google might have some funky way of reading/writing locally that isn't trivially compatible with gs4/gd. But yeah, if it's not a nightmare then this would be a really useful bit of functionality in terms of mitigating a lot of the auth pains.
