### ISSUE TITLE
Authentication via opencpu

### ISSUE THREAD

**Issue by paulvern** [tidyverse/googledrive#278]
I've been using googledrive along with opencpu for a while and as interactive authentication is not an option with opencpu I used to store a local token as .rds file and load it with the command drive_auth(use_token="mypath"). I've tried the new sintax drive_auth(token="mypath") but it seems that option doesn't work and it returns the following error message:
can't get google credentials
[...]

Is this an issue or is there something really different in the way the token is stored?

In order to elaborate the issue a little more I've the same results when trying:
drive_auth(use_oob=TRUE).
After pasting the authorization code I receive the same error message:
Error: Can't get Google credentials.
Are you running googledrive in a non-interactive session? Consider:
  * `drive_deauth()` to prevent the attempt to get credentials.
  * Call `drive_auth()` directly with all necessary specifics.

**Comment by jennybc** [comment]
Details on non-interactive auth:

https://gargle.r-lib.org/articles/non-interactive-auth.html

and on out-of-bound auth:

https://gargle.r-lib.org/articles/auth-from-web.html

> I used to store a local token as .rds file and load it with the command drive_auth(use_token="mypath"). I've tried the new sintax drive_auth(token="mypath") but it seems that option doesn't work

Is it possible that you obtained your token on R <= 3.5 and are now trying to use it on R >= 3.6? That could cause an error. It was previously silent and mysterious but as of gargle v0.4.0 (went onto CRAN today!), that should be fixed. So the first thing I recommend is to update gargle to v0.4.0 and try again.

Otherwise, I need you to set an option and try again, so we get more reporting on what's going wrong: `options(gargle_quiet = FALSE)`.

**Comment by paulvern** [comment]
It took me a while to get back to the server and update gargle to v0.4.0. As you suggested, this fixed the problem.
Thank you.

**Comment by jennybc** [comment]
> The only thing I needed to update was the required "email=" field, that was not mandatory before.

Yeah, this is an intentional choice to be less eager to use any old token we find lying around. We'd like people to become more aware of their tokens, where they live, which user they represent, and give explicit consent.

Glad this is sorted out.
