### ISSUE TITLE
drive_auth() | Error: Can only use oob authentication in an interactive session

### ISSUE THREAD

**Issue by robertoromor** [tidyverse/googledrive#287]
I am trying to deploy a shinyapp within a docker context and would like to use googledrive to store files but I am unable to connect to it in a non interactive manner. 
---
 I followed these instruction: https://gargle.r-lib.org/articles/non-interactive-auth.html#project-level-oauth-cache
In summary what I did was authorize from my RStudio server manually and stored a cache token file. While building my docker image I made sure I copied the token from the docker image directory. 

I want to know if the method that I am using is the correct one or if there is something I can do to correct getting the error "Error: Can only use oob authentication in an interactive session" when I try to autorize

```r
    options(httr_oob_default=TRUE) 
    
    options(
      gargle_oauth_cache = ".secrets",
      gargle_oauth_email = TRUE
    )
    
    googledrive::drive_auth()
    
   drive_find(n_max = 5)
```

**Comment by jennybc** [comment]
A couple of things.

googledrive uses gargle and gargle consults the option named `"gargle_oob_default"`, but, yes does fall back to `"httr_oob_default"`. If you're going to explicitly set it, I'd favour the gargle option.

But in any case, this should not matter, because this option should only be important at _initial token acquisition_ (so your initial interactive procedure) and not later, when you are trying to refresh (on docker).

The fact that there seems to be an attempt to _initiate_ auth inside docker suggests that your pre-acquired token is not being found.

So first I would suspect some sort of path or permissions problem. I'd try to troubleshoot with docker but without Shiny in the mix.

Use `gargle::gargle_oauth_sitrep()` to get an overall situation report re: where gargle is looking for tokens and what it finds there.

Also setting the option named `"gargle_quiet"` to `FALSE` can cause gargle to emit much more information about what it's trying and what succeeds/fails.
