### ISSUE TITLE
Unable to transfer file ownership

### ISSUE THREAD

**Issue by tklebel** [tidyverse/googledrive#297]
I initially wanted to delete files from a shared folder which I do not own. While trying to create a reprex, I ran into this issue. I'm simply unable to transfer file ownership.

The example is adapted from the docs for `drive_share()`.

``` r
library(googledrive)

file <- drive_upload(
  drive_example("chicken.txt"),
  name = "chicken-share.txt",
  type = "document"
)
#> Local file:
#>   * C:/Users/ThomasKlebel/Documents/R/R-3.6.2/library/googledrive/extdata/chicken.txt
#> uploaded into Drive file:
#>   * chicken-share: 1pJtiOWHvAesRzcHtUoNrGa3vCIOjeueLIjBcZEv9V6I
#> with MIME type:
#>   * application/vnd.google-apps.document

## Let a specific person comment
file <- file %>%
  drive_share(
    role = "owner",
    type = "user",
    emailAddress = "XXXXXXX@gmail.com" # an address of someone else
)
#> Error: Client error: (403) Forbidden
#>   *       domain: global
#>   *       reason: forbidden
#>   *      message: The transferOwnership parameter must be enabled when the permission role is 'owner'.
#>   * locationType: parameter
#>   *     location: transferOwnership
```

<sup>Created on 2020-02-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jennybc** [comment]
`drive_share()` is documented to wrap the [`permissions.update` endpoint](https://developers.google.com/drive/v3/reference/permissions/create).

Here's your error message:

```
#> Error: Client error: (403) Forbidden
#>   *       domain: global
#>   *       reason: forbidden
#>   *      message: The transferOwnership parameter must be enabled when the permission role is 'owner'.
#>   * locationType: parameter
#>   *     location: transferOwnership
```

I look up the `transferOwnership` parameter in the endpoint docs and find this:

```
transferOwnership | boolean | Whether to transfer ownership to the specified
                              user and downgrade the current owner to a writer.
                              This parameter is required as an acknowledgement
                              of the side effect. (Default: false)
```

`drive_share()` accepts additional parameters via `...`. You should send `transferOwnership = TRUE` as part of your call. So something like this:

```
drive_share(
  role = "owner",
  type = "user",
  emailAddress = "someone.else@example.com",
  transferOwnership = TRUE
)
```

**Comment by tklebel** [comment]
Right. Should have read the docs more carefully. 

Would you be ok with a pull request that adds this as an example to the documentation, or would this add too much clutter to the examples in your eyes? (I tend to look at the examples carefully and missed the link to the API docs).

An alternative could also be to catch this case and throw a more specific error message, potentially even before calling the API?

**Comment by jennybc** [comment]
I have a pretty strict policy about _not_ wanting many functions to take `...` this way and about not documenting what can go in `...`. I exposed it here just because there are some edge cases (yours is a good example) that I wanted to allow but not actually support.

I have learned the hard way that it is futile to document someone else's API or to document aspects you don't depend on / explicitly support. So I'm afraid you've just run up against an example where, to do what you need with googledrive, you do need to learn a bit about this endpoint. And googledrive _does_ work for this case. But I'm not willing to take more responsibility for it, i.e. trying proactively document the special case of transferring ownership or to catch and error before the API errors.

**Comment by tklebel** [comment]
I get your point, thanks for explaining your rationale!
