### ISSUE TITLE
several issues with drive_mkdir()

### ISSUE THREAD

**Issue by douglascm** [tidyverse/googledrive#299]
>  Error: Parent specified via `path` doesn't uniquely identify exactly one folder or Team Drive.

> Error in add_id_path(nodes, root_id = root_id, leaf = leaf) : !anyDuplicated(nodes$id) is not TRUE

Getting both these errors while trying to create folders using

`drive_mkdir(name,path/to/folder)`

other functions work just file, such as drive_upload

**Comment by jennybc** [comment]
Sounds like a problem reported in #272 #277 #279 and #281.

And, I believe 🤞, fixed via:
https://github.com/tidyverse/googledrive/commit/e56b3f5d2e7b3a421115a1858df7456857478f5a

You'll need to install the dev version from GitHub in order to get this fix because there hasn't been a CRAN release with it yet.
