### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by shahab3476** [tidyverse/googledrive#309]
When trying to login to get a new token I get the following error message

![image](https://user-images.githubusercontent.com/8781789/82766277-8fd4c380-9dd2-11ea-80ec-227a71f36110.png)

This has just started a few days ago.

**Comment by jennybc** [comment]
I deleted some old credentials a couple of days ago and it sounds like you were still using a cached token associated with them or an old API key. When googledrive v1.0.0 was released in August 2019 we switched to a new built-in OAuth app and API key. You can read about that release here:

https://www.tidyverse.org/blog/2019/08/googledrive-1-0-0/

The fix for you is to update googledrive and re-auth.

In general, we provide built-in creds as a convenience for users and to get people up and running quickly. But we may choose or be forced to roll credentials at any time. So if this is a problem, e.g. for something that is running "in production" (whatever that means for you), that's a signal you should bring your own OAuth app or API key.

But if the occasional hiccup is OK and the answer is "update googledrive and re-auth", then just do that every few months or years and carry on.
