### ISSUE TITLE
`drive_upload()` fails intermittently with Error 408 (Request timeout)

### ISSUE THREAD

**Issue by Arf9999** [tidyverse/googledrive#314]
I have a script that uploads a number of .csv and .rds files to Google drive.  In order to do this, I have a script that identifies all these files (via the dir() command) and then iterates along that list to upload them.

However, I find that the upload fails intermittently when uploading .rds files.

The error that is returned is as follows:

```
Error: Expected content type 'application/json' not 'text/html'.
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 408 (Request Timeout)!!1</title>
  <style>...
```
Since this is intermittent, and doesn't happen with the same files (although it seems always with .rds files, not .csv), I don't have a reprex to share.

I've tried to specifically set the `type= "zip"` to see if this is the problem, but still have the same issue.

Any ideas?

**Comment by jennybc** [comment]
The dev version of googlesheets4 (a sibling package to googledrive) now uses a dev **branch** of gargle (https://github.com/r-lib/gargle/tree/retry), the underlying package that handles auth and request basics for both packages. The `retry` branch of gargle has implements a basic retry strategy that has helped immensely with handling intermittent failure like this in googlesheets4.

The switch happened here:
https://github.com/tidyverse/googlesheets4/commit/5bceac261e9af6f9eb1b902f75d3c2f54cb20d4b

I'm not working on googledrive right now, but depending on your motivation level, you could try similar in googledrive and see if it helps. It's a bit odd that you're getting an html error vs. json. That makes it look like an error meant to happen in some sort browser-mediated interaction, vs API.

**Comment by Arf9999** [comment]
Thanks, I'll give that a try.

**Comment by Arf9999** [comment]
I have to report back that it didn't work.  And that my suspicion that it was only .rds files was false. I now have a .csv file displaying the same issue - and  consistently - so I can do a bit of digging to find out why.

**Comment by jennybc** [comment]
> I have to report back that it didn't work

Can you be more specific about what exactly you tried?

**Comment by jennybc** [comment]
I am willing to speculate that the reason this "didn't work" is that currently `gargle::request_retry()` only retries on 429 (quota exhaustion). I have never actually seen quota exhaustion with the Drive API since the limits are 2 orders of magnitude higher than for Sheets.

As of the time of writing, Drive quotas:
* Queries per day: 1,000,000,000
* Queries per 100 seconds per user: 10,000
* Queries per 100 seconds: 10,000

In sharp contrast to the Sheets quotas (https://developers.google.com/sheets/api/limits):
* "This version of the Google Sheets API has a limit of 500 requests per 100 seconds per project, and 100 requests per 100 seconds per user. Limits for reads and writes are tracked separately. There is no daily usage limit."
* Read requests per minute: 600
* Read requests per minute per user: 60
* Read requests per day: Unlimited
* Write requests per minute: 300 	
* Write requests per minute per user: 60
* Write requests per day: Unlimited

To address this issue here, I would need to generalize `gargle::request_retry()`:

https://github.com/r-lib/gargle/issues/169

**Comment by jennybc** [comment]
This is really a gargle issue and it's already captured as part of https://github.com/r-lib/gargle/issues/169. There is certainly good evidence that we could / should be retrying on 408.
