### ISSUE TITLE
Unshare a folder or change the role

### ISSUE THREAD

**Issue by kpmainali** [tidyverse/googledrive#318]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Two issues: 

(1) how do you unshare a folder to a personal email address by completely revoking the role previously assigned with drive_share()?

(2) once you grant a role of editor to a personal email address, how do you change the role to reader? By rerunning the drive_share() with new role should solve the problem. When I change the role from reader to writer, it works fine. When I change it from writer to reader, although the console window says the "Permission updated", the permission is not updated.

Thanks. 

```r
# insert reprex here
```

**Comment by jennybc** [comment]
This is being tracked in #180. There is not currently a high-level interface for modifying permissions. I have recently also had a need to *edit* or *delete* permissions, so that makes it more likely I'll work on this soon-ish. But at the moment, one would have to do in the browser or build up one's own function with the low-level tools here.
