### ISSUE TITLE
Add description to to `drive_reveal()`

### ISSUE THREAD

**Issue by FedericoTrifoglio** [tidyverse/googledrive#329]
Suggesting to add "description" as an option to the what argument of drive_reveal

For now, I've achieved it by doing this. 

  drive_reveal_description <- function (file) 
  {
    confirm_dribble(file)
    if (no_file(file)) {
      return(put_column(dribble(), nm = "description", 
                        val = character(), .after = "name"))
    }
    googledrive:::promote(file, "description")
  }

Is there a better way?

**Comment by jennybc** [comment]
Yeah, that looks about right and I assume you're getting the result you want.

Seems reasonable. But instead of making the list of acceptable `what` values larger and larger, maybe it makes sense to allow unmatched values if they work simply with `promote()`. I would keep the existing `what` values, which mostly require special handling.

I'm just starting a big update here and will do something about this once I dig in.

**Comment by FedericoTrifoglio** [comment]
Thanks for looking into this! That's very much appreciated.
