### ISSUE TITLE
Working with Multiple Files in a Shared Drive Folder

### ISSUE THREAD

**Issue by huixinz2** [tidyverse/googledrive#372]
I am trying to use the `map()` function, as described in this [article](https://googledrive.tidyverse.org/articles/articles/multiple-files.html#upload), to update the metadata for multiple files in a folder within a shared drive. The specific metadata update is to make all these files read-only, as addressed in issue #370. I'm using the codes below to update all the files in a folder called `chicken`, which is in a shared drive. 

```r
drive <- shared_drive_get("shared_drive")
subdirectory <- drive_get("chicken", shared_drive = drive)
drive_ls(subdirectory)

files_to_update <- drive_ls(path=subdirectory, recursive = T)
``` 
Up to this point, all seems good. However, I am getting an error message in the following step: 

```r
files_to_update <- map(files_to_update, ~ drive_update(.x,
                                                   contentRestrictions = list(list(readOnly = TRUE))))
```
The error message read "`file` does not identify at least one Drive file." Is it because I am not using `drive_ls` correctly to identify multiple files? How can I address this?

**Comment by jennybc** [comment]
Just from reading this code (as I cannot actually run it, because it's not really a reprex), I am guessing ....

`files_to_update` is a `dribble`, one row per file

`map(files_to_update, ...)` will map OVER THE COLUMNS of `files_to_update`, which makes no sense.

You probably need to work just with the ids? Something like `map(files_to_update$drive_id, ...)`.

This is what the section that begins "Now let’s reflect on the files object returned by this operation...." is getting at.

In the future, this is a lot easier if there's code I can actually run, not just run it in my head.

**Comment by huixinz2** [comment]
Thank you so much! `map(files_to_update$drive_id, ...)` works. Apology that I didn't figure out how to create a reprex that involves a shared drive. I'll read up on it!
