### ISSUE TITLE
drive_share suppress email notificaiton

### ISSUE THREAD

**Issue by bllittle** [tidyverse/googledrive#373]
I've been looking through the vignettes and documentation on the parameters this accepts and don't see a means of suppressing sending out an email notification when sharing. A scenario where this would be useful: An organization where many folders are shared, but each unit may have unique permission requirements. However, there may be "super users" who would need access to folders across units (in our case, we are a large school district with folders set up for each school so principals and other administrators have access to their school's folders but not another school's -- but people in Central Office would need access to groups of schools). We don't want the "super users" to be inundated with email notifications. 
If this is not currently available, perhaps this is more a feature enhancement request for when permissions are addressed in the future (I've noticed that is in the plans). If it is available and not documented, please share an example.. 

Thank you. 
```r
# insert reprex here
```

**Comment by jennybc** [comment]
The `drive_share()` documentation reveals that this function wraps the `permissions.create` endpoint:

https://googledrive.tidyverse.org/reference/drive_share.html

https://developers.google.com/drive/api/v3/reference/permissions/create

There I see a parameter named `sendNotificationEmail` which seems to control what you want. Therefore I'd try something along these lines:

``` r
drive_share(..., sendNotificationEmail = FALSE)
```

I give the surrounding detail because many googledrive functions expose a `...` argument to allow access to the often-numerous, often-changing parameters available for individual API endpoints. I deliberately do not explicitly expose or document them all myself, as it's not sustainable. This strategy re: reading about the endpoint and passing info via `...` is likely to come up repeatedly with advanced use of the googledrive package.

**Comment by bllittle** [comment]
Thanks! I appreciate that. I knew of the parameter in the API, but wasn't
sure how to pass it along via the googledrive package function.  I'll pay
closer attention to the ... possibilities in in the future should the need
to utilize other less frequently used parameters come up.
