### ISSUE TITLE
using drive_find(q = "fullText contains 'insert_anything_here'") always returns an error

### ISSUE THREAD

**Issue by dungates** [tidyverse/googledrive#374]
No matter what I query with fullText does not appear to work and the error is somewhat nonsensical. There is no sorting being done on my end. I also know that I have google sheets with the word "student" in them and have tried many other queries with the same result, even when I just make it as simple as the letter "e" instead of "student". I have tried different accounts as well as restarting RStudio.

---

Brief description of the problem

``` r
googledrive::drive_find(q = "fullText contains 'student'")
#> ! Using an auto-discovered, cached token.
#>   To suppress this message, modify your code or options to clearly consent to
#>   the use of a cached token.
#>   See gargle's "Non-interactive auth" vignette for more details:
#>   <https://gargle.r-lib.org/articles/non-interactive-auth.html>
#> ℹ The googledrive package is using a cached token for
#>   'duncan.gates@teachinglab.org'.
#> Error: Client error: (403) Forbidden
#> Sorting is not supported for queries with fullText terms. Results are always in
#> descending relevance order.
#> • domain: global
#> • reason: forbidden
#> • message: Sorting is not supported for queries with fullText terms. Results are
#>   always in descending relevance order.
#> • locationType: parameter
#> • location: orderBy
```

<sup>Created on 2021-09-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jennybc** [comment]
The error is about `orderBy` which is an optional parameter we send because it usually helps make the result more useful:

https://googledrive.tidyverse.org/reference/drive_find.html#sort-order

> To suppress sending `orderBy` at all, do `drive_find(orderBy = NULL)`.

Therefore I tried

``` r
drive_find(q = "fullText contains 'meeting'", orderBy = NULL)
```

and it works. I don't think we should suppress `orderBy` automatically, in general, because `orderBy` works well with the vast majority of queries. So we'll just have to chalk this up as something one must do when writing your own `q` query of the `fullText contains 'whatever'` form.
