### ISSUE TITLE
Drive shared folder shortcut not working properly

### ISSUE THREAD

**Issue by jlatapiattp** [tidyverse/googledrive#396]
I'm trying to read files in a shared folder in drive, and i can get to the folder

`drive_ls('~/Shared Folder/')`

```
ℹ Parent specified via `path` is a shortcut; resolving to its target folder

ℹ Resolved 1 shortcut found in 1 file:

• Shared Folder <id: 1P9vpcQQxzElp9kk8VTIRXGjPAYO0NQNq> ->
  Shared Folder <id: 1M--hOkbgk-24hgbISNonxIRwMAGjkws_>
```

But if i try to get to a subfolder or get a file from said folder, it can't find it.

`drive_ls('~/Shared Folder/Dataset')`

```
Error in `as_parent()`:
! Parent specified via `path` is invalid:
✖ Does not exist.
Traceback:

1. drive_ls("~/Shared Folder/Dataset")
2. as_parent(path)
3. drive_abort(c(invalid_parent, x = "Does not exist."))
4. cli::cli_abort(message = message, ..., .envir = .envir)
5. rlang::abort(message, ..., call = call, use_cli_format = TRUE)
6. signal_abort(cnd, .file)
```

**Comment by gorkang** [comment]
Can confirm this. On my computer, using `drive_ls()` on a folder below the root folder, won't work.

```
library(googledrive)
drive_ls("~/FOLDER/") # Works
drive_ls("~/FOLDER/SUBFOLDER/") # Stalls
```

Trying to get to the bottom of it, I managed to get to `as_dribble()` as a potential culprit. But not sure how exactly.

```
as_dribble("~/FOLDER/") # Works
as_dribble("~/FOLDER/SUBFOLDER/") # Stalls
```

**Comment by jennybc** [comment]
This scenario is what's referenced here:

https://github.com/tidyverse/googledrive/blob/0bb007030f89fc1877357eb96d2eec327e27ef12/R/drive_get_path.R#L91-L93

and here:

https://github.com/tidyverse/googledrive/blob/0bb007030f89fc1877357eb96d2eec327e27ef12/R/drive_get_path.R#L209-L210

It's not easy to facilitate full access by file "path" when a non-terminal path element is a shortcut to a shared folder. (The Drive API offers _no_ support, really, for access by file name or path. Those features are delivered entirely by the googledrive package.)

In this case, you're going to have to do a little more work to get to a file ID for the folder of interest, then `drive_ls()` that.

I have a naturally-occurring example of this myself and here's the code that worked.
`"~/JobDescriptions/"` is a shortcut in My Drive to a folder owned by somebody else but that is shared with me. It has exactly one subfolder, so this command gets that as a `dribble`.

``` r
subfolder_of_shortcutted_shared_folder <- drive_ls("~/JobDescriptions/", type = "folder")
```

If there is more than one subfolder in your case, you will need to add more arguments to the implicit `drive_find()` inside the `drive_ls()`, such as `pattern` or `corpus`, to narrow things down. Or filter the returned `dribble` "by hand" until it has 1 row.

The important part is that you have to get your hands on the file ID of the subfolder of interest. Then apply `drive_ls()` to a file ID or a 1-row `dribble`:

``` r
drive_ls(subfolder_of_shortcutted_shared_folder)
```

This is not getting fixed any time soon, because it's not very easy to get a file or folder by a non-canonical path.
