### ISSUE TITLE
Issue with authorization on  a remote server and attempts to bypass problems using gargle

### ISSUE THREAD

**Issue by tnieuwe** [tidyverse/googledrive#410]
Hello,

I'm trying to authorize myself in browser to access some files in googledrive and I am  still unable to access my drive after trying multiple methods.

Things I've tried:

1. 
 I initially tried to use basic `drive_auth()` which gave me :
```
Use a local file ('.httr-oauth'), to cache OAuth access credentials between R sessions?

1: Yes
2: No
```
I selected 1 and attempted to run `drive_find(n_max = 10)` which returned
```
Error in `gargle::response_process()`:
! Client error: (403) Forbidden
Request had insufficient authentication scopes.
PERMISSION_DENIED
• message: Insufficient Permission
• domain: global
• reason: insufficientPermissions
Backtrace:
 1. googledrive::drive_find(n_max = 10)
 2. googledrive::do_paginated_request(request, n_max = n_max, n = function(x) length(x$files))
 3. gargle::response_process(page)
 ```
2. 
 I realized this was a permissions/authorization issue. I decided to test drive_auth on my local machine which worked fine. I then turned to https://gargle.r-lib.org/articles/auth-from-web.html, as I learned the auth process was a wrapper around gargle. After running `drive_deauth()` I attempted to run `drive_auth()` this time with `use_oob = TRUE`. I still had the same issue however. Of note, I had not at any point been prompted to another website to continue authorization. 

3. 
I then decided to see if I could circumvent the issue by creating a token directly through gargle using:
```
gargle::credentials_user_oauth2(
   scopes = "https://www.googleapis.com/auth/drive"
)
```
This redirected me to a website where I gave permissions for drive access and copied the authorization code, pasted it into R,  thus creating a token that could be seen using `gargle::gargle_oauth_sitrep()`. I then used drive_auth with the `token = token_path` the `token_path` pointing directly to the newly created gargle token. This however did not work.

I am sorry if I've been going about this the wrong way, but I'm somewhat at a loss of what to do at this point, and apologies if this is better handled on the gargle github, I could move my question there if necessary. Thank you for any help you can give me.

Best,
Tim

**Comment by jennybc** [comment]
Can you tell me more about "on a remote server"?

Are you on Google Cloud?

BTW gargle just had a release, so, no matter what, please install the new version of gargle.

I suspect that you are on Google Cloud and you are being automagically auth'ed as a service account. But it sounds like you want to auth as yourself, i.e. a normal user. But I'll wait for you to provide more concrete details.

**Comment by tnieuwe** [comment]
Hi Jenny,

Sorry for not giving more of an explanation. The remote server is hosted by Google Cloud technically through Terra. And what your describing sounds correct. The google drive I'm trying to use is the one associated with the google account I am using in the remote server, which also accesses the google bucket without issue. Are there more details you need from me?

**Comment by tnieuwe** [comment]
Hi Jenny,

Sorry for not giving more of an explanation. The remote server is hosted by Google Cloud technically through Terra. And what you're describing sounds correct. The google drive I'm trying to interact with is associated with the google account I am using in the remote server, which also accesses the google bucket without issue. Is there a different approach I need to take, and are there more details you need from me? 

I also will install the new gargle. Also pardon my initial closing I miss-clicked.

Thank you,
Tim

**Comment by jennybc** [comment]
OK so what we really need to settle is *who* you want to auth as. The default behaviour of gargle and, therefore, googledrive is different on your local computer vs. on Google Cloud and that's what you're experiencing and, understandably, being a bit puzzled by. To jump ahead, I can give some info on the two possible answers.

**Auth as a service account**: This is the path of least resistance if your code is running on Google Cloud and certainly seems to be what I see happening above, in your first attempt. Here are some interesting bits of code for you to run on Cloud (Terra, in your case) to better understand where things stand:

``` r
gargle::gce_instance_service_accounts()
```

This is a new function in gargle 1.3.0 and will reveal the service accounts you can auth as on Cloud (Terra, in your case). This should also reveal the *scopes* associated with those service accounts, which will be interesting given this from above: `Request had insufficient authentication scopes`.

If you possibly can use a service account, that is the "right" thing to do on Cloud. But it's possible you still need to do more set up around your VM or service accounts to have the necessary permissions.

**Auth as yourself, i.e. a normal user**: This requires a bit of explicit effort on Cloud, because you need to tell gargle to *not* auth as the default service account. In your second attempt above, this seems to be what you're trying to do, but it didn't work. I'd need to see more details about that to help straighten it out.

This is a long issue thread (https://github.com/r-lib/gargle/issues/187) but is currently the best account of how to skip over the default service account and instead auth as a user. I know the docs (and probably tooling) around this need to get better.

Hopefully this helps elicit what your actual goal is so we can get you unstuck.

**Comment by tnieuwe** [comment]
Hi Jenny,

Thank you for your help so far!
You are correct I am currently running on a service account that has access with the following scopes:

```
https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/userinfo.profile
```

However the service account is managed by Terra, and while I am going to reach out to them to see how I can add more scopes, I'm going to move forward for now trying to Auth as a normal user.

What details will you need for Auth-ing as a normal user?

 I'll also try to use the mentioned gargle thread, I was trying to follow the fix here: https://github.com/r-lib/gargle/issues/187#issuecomment-1245696707 but I'm not sure where the user acquired a "`.rds`" file for the token. Thank you for you patience.

Best,
Tim

**Comment by jennybc** [comment]
One way to auth as a normal user is to explicitly disable GCE auth. I think it's the simplest approach today.

This should remove `credentials_gce()` from the credential fetching registry, allowing a subsequent attempt to auth to fall through to the regular user flow. So put this near the top of a script, i.e. before any calls to googledrive.

``` r
gargle::cred_funs_add(credentials_gce = NULL)
```

Here's where all the functions re: the registry are documented: https://gargle.r-lib.org/reference/cred_funs.html

While you sorting this out, you could use `gargle::cred_funs_list()` just to gain more visibility into what's going on.

**Comment by tnieuwe** [comment]
That seemed to work perfectly! I ran `gargle::cred_funs_add(credentials_gce = NULL)`, attempted to use `googledrive::drive_ls()`, was asked to authenticate myself, and now I have full drive access.  Thank you so much for both your help here and on the development of these packages.

**Comment by jennybc** [comment]
Glad to hear this is sorted out. I am going to expand gargle's docs around Google Cloud / Google Computer Engine and friends, so this has been a good concrete example for me to help work through.
