### ISSUE TITLE
Feature request: Support for "headless" authentication now that "OOB flow" has been blocked

### ISSUE THREAD

**Issue by bpoliakoff** [tidyverse/googledrive#422]
When I attempt to use the googledrive library on a *server*, and trigger an authentication with "drive_find(n_max = 25)", the library opens a new browser tab to process the oauth request, but it's blocked by Google:

Details: 
```Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob
[Related developer documentation](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration)```

Is there any hope for migrating the authentication flow to one of the one of the alternatives spelled out on Google's "Out-Of-Band (OOB) flow Migration Guide" (https://developers.google.com/identity/protocols/oauth2/resources/oob-migration)?

**Comment by jennybc** [comment]
Yes, I am well aware of this situation.

It has already been addressed by gargle 1.3.0 (which handles auth for googledrive and more), released in January.

The most recent version of googledrive requires that version of gargle, so that will force even more folks to upgrade.

If you want to read more about the history, see:

https://gargle.r-lib.org/news/index.html#gargle-130

https://github.com/r-lib/gargle/pull/214
