### ISSUE TITLE
change `drive_file()` to output a dribble

### ISSUE THREAD

**Issue by LucyMcGowan** [tidyverse/googledrive#62]
* `drive_file()` should output something similar to a single row output from `drive_list()`
* perhaps develop a drive tibble (dribble) method
* switch to gfiles as only an internal thing

**Comment by jennybc** [comment]
Ok let's imagine that a dribble is the main object a user handles that describes one or more Drive files. It is a tibble. This seems like a weird choice. Why do we do that? So that the object type for `n = 1` files and `n > 1` files is the same, i.e. it acts sort of like a custom vector type.

There should be a small number of simple atomic variables that are guaranteed to be there, maybe just file id and name. Then there should be a list-column that holds one [Drive file resource](https://developers.google.com/drive/v3/reference/files) per file. That is, of course, what `gfile` already is. I'm just proposing that we rename it and think of it this way. Unclear how much to formalize that.

We prefer a dribble (one file = one row) to a list of lists (one file = one top-level component), because it makes the most important information (file id and name) easier to access and get in front of your eyeballs.

**Comment by jennybc** [comment]
If we implement this, then it makes it much more natural for most functions to be vectorized, i.e. to cheerfully work on multiple Drive files.

**Comment by LucyMcGowan** [comment]
I wonder if we end up vectorizing all of the functions if there is even a need for `drive_file()` since it's essentially `drive_list()` but for a single file?
