### ISSUE TITLE
File identification

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#76]
We probably want to do some renaming. `drive_from_path()` and `drive_from_id()` better describe what the current `drive_path()` and `drive_get()` functions do. Too clunky though?

It also seems odd that those functions can't take a vector of inputs, but `as_dribble.character()` and `as_dribble.drive_id()` can. Think about this.

All the ways to identify files:

  * `drive_path()`
  * `drive_get()`
  * `drive_search()`
  * `drive_ls()`
  * `as_dribble()` on character vector and `drive_id` vector and (for internal use) list of Files Resource objects or `dribble`

The ones that start with `drive_` are conceived to be called directly by a user. `as_dribble()` is generally used internally to pre-process user input describing the file(s) to act on.

**Comment by LucyMcGowan** [comment]
would it be very strange if `as_dribble()` was the function we encouraged the user to use? 

*pros*: it could  be a bit simpler - this is basically converting whatever you have (path, id, list) to a `dribble` that we can recognize with some basic checks. Also, it works on vectors, which seems natural. The workflow would basically be I have some "thing" & I need to register it as a `dribble` (but if I use a drive function explicitly, it will be registered automatically).

*cons*: maybe it's confusing because the user isn't explicit about what they think they're inputting? Also if they wanted to input an id they'd have to use `drive_id() %>% as_dribble()`.

**Comment by jennybc** [comment]
> would it be very strange if `as_dribble()` was the function we encouraged the user to use?

Maybe not. I feel like we're still converging on the most natural way for people to get a hold on the files they want to work on. The good news is that all of it is now possible and fairly smooth.
